POST http://localhost:8080//setTestData
Content-Type: application/json

###

DELETE http://localhost:8080//grand-parent/1


###
PUT http://localhost:8080//grand-parent/80/85




select * from grand_parent;
select * from parent;
select * from child;